version: '2'
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app/
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: npm run start
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "orders"
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
    volumes:
      - mysql-orders:/var/lib/mysql
volumes:
  mysql-orders: